### ISSUE TITLE
How to run the program?

### ISSUE THREAD

**Issue by hideoshiraishi** [p3et/dmgm#20]
I am curious to run the program to find subgraphs in my multigraphs in my windows environment.
I have been using R/python but first time to run java, and am facing very basic issue to run the program in my IDE (VS Code).

As a test, I just copied and pasted your scripts in "Implementation and API" in the following class.

public class graph {

scripts in "Implementation and API"

}

However, VS Code returns lots of errors as attached.
I suppose I do not follow appropriate way to run it correctly.

![error](https://github.com/p3et/dmgm/assets/41860959/975bb493-03e5-4718-9ac7-e3f9bdd28d12)

I also downloaded the ZIP file from "<> Code" and found several .java files in 'dmgm-master\src\main\java\org\biiig\dmgm\impl\model' a nd other folders. However it could not be run in my IDE as well.

I suppose I am taking completely wrong way to run it. Sorry for asking the basic, but could you please kindly let me know how to run the program appropriately?

**Comment by hideoshiraishi** [comment]
I tried to compile the project using Maven under VS Code as illustrated below.
I downloaded and unzip "dmgm-master" folder, then "open a Java project folder" in VS Code.

![image](https://github.com/p3et/dmgm/assets/41860959/69b13286-ded9-4fac-926d-0e1d703e8fa9)

In the left-side column it found "demo" and "dmgm" folder which contains "pom.xml" file and I "clean", "compile" and "install" it in the both folders. It succeeded in "demo" folder and "demo-1.0-SNAPSHOT.jar" appeared in "dmgm-master\demo\target" folder. I ran it via powershell "java -jar .\demo-1.0-SNAPSHOT.jar" but nothing happened.
In "dmgm" folder "compile" and "install" returned errors and did not create ".jar" file.

I pasted a part of the error messages:

[INFO] Running org.biiig.dmgm.impl.operators.patternmining.SimFreqThresholdTest
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0 s <<< FAILURE! -- in org.biiig.dmgm.impl.operators.patternmining.SimFreqThresholdTest
[ERROR] org.biiig.dmgm.impl.operators.patternmining.SimFreqThresholdTest.mine08 -- Time elapsed: 0 s <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.biiig.dmgm.impl.operators.patternmining.FrequentSimpleSubgraphs 
        at org.biiig.dmgm.impl.operators.patternmining.CollectionFrequentSubgraphsMinerBuilder.simple(CollectionFrequentSubgraphsMinerBuilder.java:47)
        at org.biiig.dmgm.impl.operators.patternmining.SimFreqThresholdTest.getOperator(SimFreqThresholdTest.java:27)
        at org.biiig.dmgm.impl.operators.patternmining.SubgraphMiningThresholdTestBase.mine(SubgraphMiningThresholdTestBase.java:46)
        at org.biiig.dmgm.impl.operators.patternmining.SubgraphMiningThresholdTestBase.mine08(SubgraphMiningThresholdTestBase.java:39)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: Could not initialize class org.biiig.dmgm.impl.operators.patternmining.SubgraphMiningBase [in thread "main"]
        at org.biiig.dmgm.impl.operators.patternmining.CollectionFrequentSubgraphsMinerBuilder.simple(CollectionFrequentSubgraphsMinerBuilder.java:47)
        at org.biiig.dmgm.impl.operators.patternmining.SimFreqPatternTest.lambda$getOperator$0(SimFreqPatternTest.java:29)     
        at org.biiig.dmgm.DmgmTestBase.runAndTestExpectation(DmgmTestBase.java:141)
        at org.biiig.dmgm.impl.operators.patternmining.SubgraphMiningPatternTest.testCircleWithBranch(SubgraphMiningPatternTest.java:67)
        ... 23 more


Appreciated if I am doing something wrong.

Maven 3.9.3
Visual Studio Code 1.80.00
Windows 10 Home, version 22H2

**Comment by hideoshiraishi** [comment]
I could `install` both in `demo` and `dmgm` folders which returned `dmgm-0.1-SNAPSHOT.jar` under `.\demo\target` and `./target` folder after changing JDK/JRE version. I ran the following command in the prompt but returned the following error.

```
D:\mavenRepo\localRepository\dmgm-master\target>java -jar dmgm-0.1-SNAPSHOT.jar
no main manifest attribute, in your dmgm-0.1-SNAPSHOT.jar
```

I cannot find .mf file in the folder after installation.
Anything wrong?
